V0.3

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -11,9 +11,9 @@
 #
 ############################################################################
 
-version=0.2
+version=0.3
 
-chmod 755 scripts/*
+chmod 755 script/*
 
 while :
 do
@@ -36,14 +36,13 @@ do
 	read tntopt
 	echo
 	echo
-	echo
 
 	case "$tntopt" in
 	    1 ) clear; script/update $version; continue;;
 	    2 ) clear; script/app $version; continue;;
 	    k ) clear; cd ~/kitchen; ./menu; clear; continue;;
-	    x ) clear; echo "Goodbey !"; echo; exit 1;;
-	    * ) clear; echo "Invalid option"; continue;;
+	    x ) clear; echo -e "\033[31mGoodbey !\033[0m"; echo; exit 1;;
+	    * ) echo; echo -e "\033[31mInvalid option !!!\033[0m"; continue;;
 	esac
 done
 
