V.0.011
+New Theme
+New Menu for app [TNT Store]
+Readapt all menu for app...
+New script for colorization.
+Add or fix some colors...

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -11,102 +11,88 @@
 #
 ############################################################################
 
-version=0.010
+version=0.011
 
-
+source script/colors
+echo -e "$NORMALE"
 
 if [ ! -e menu ]
 then
-  echo
-  echo "Ensure you run this file from the SAME folder as where it was"
-  echo "installed, otherwise TNT will have problems run."
-  echo "After you 'cd' to TNT folderStart TNT"
-  echo "Start TNT with the ./menu command!!!"
-  exit 0
+	echo
+	echo -e "$Red" "Ensure you run this file from the SAME folder as where it was"
+	echo -e "installed, otherwise TNT will have problems run."
+	echo -e "After you 'cd' to TNT folderStart TNT"
+	cho -e "Start TNT with the ./menu command!!!" "$NORMAL"
+	exit 0
 fi
 
+chmod 755 android_tools/*
 chmod 755 script/*
-script/check_install_dir
+chmod 755 tnt_store/*
+chmod 755 update/*
 
 if [ "$?" == "1" ]
 then
-  exit 0
+	exit 0
 fi
 
 while :
 do
 	clear
-	online_vers=`script/check_update`
+	online_vers=`update/check_update`
 	rm -f Last_CHANGELOG
 	last_vers=`echo $online_vers | sed -e 's/.*Version[ ]*\([0-9]*.[0-9]*\) (.*/\1/g' -e 's/[ ]*//g'`
+	curr_major=`echo $version | sed 's/\([0-9]*\).[0-9]*/\1/'`
+	curr_minor=`echo $version | sed 's/[0-9]*.//'`
+	last_major=`echo $last_vers | sed 's/\([0-9]*\).[0-9]*/\1/'`
+	last_minor=`echo $last_vers | sed 's/[0-9]*.//'`
+	update=1
+	if [ $curr_major -gt $last_major ]
+	then
+		update=0
+	else
+	if [ $curr_major -eq $last_major ]
+	then
+		if [ $curr_minor -ge $last_minor ]
+		then
+			update=0
+		fi
+	fi
+fi
+if [ $update == 0 ] 
+then
+	echo
+else
+	echo -e "$Cyan" "==InfoBox===================================================" "$NORMAL"
+	echo -e "$Red" "New Update online (V.$last_vers). Option (n) = Direct UPDATE" "$NORMAL"
+fi
+echo -e "$Cyan" "============================================================" "$NORMAL"
+echo -e "     $Green_BU"" ToolsNeoTeam V.$version - by NeoCooler aka krisjanne" "$NORMAL"
+echo -e "$Cyan" "============================================================" "$NORMAL"
+echo -e "$Cyan" "->$NORMAL$White MAIN MENU$NORMAL"
+echo -e "$Magenta"
+echo -e "     1 -$White_K TNT Store.$Magenta"
+echo -e "     2 -$White_K Android Tools.$Magenta"
+echo
+echo -e "     u -$White_K Updates.$Magenta"
+echo
+echo -e "     x -$White_K Exit.$Magenta"
+echo -e "$NORMAL"
+echo -e -n "$Yellow" " Choose option:" "$White_B"
+read tntopt
+echo
+echo -e "$NORMAL"
 
-  	curr_major=`echo $version | sed 's/\([0-9]*\).[0-9]*/\1/'`
-  	curr_minor=`echo $version | sed 's/[0-9]*.//'`
-
-  	last_major=`echo $last_vers | sed 's/\([0-9]*\).[0-9]*/\1/'`
-  	last_minor=`echo $last_vers | sed 's/[0-9]*.//'`
-
-  	update=1
-
-  	#
-  	# Compare our version with version online
- 	#
-  	if [ $curr_major -gt $last_major ]
-  	then
-  	  update=0
- 	 else
-
- 	  if [ $curr_major -eq $last_major ]
- 	   then
- 	    if [ $curr_minor -ge $last_minor ]
-  	    then
-  	      update=0
-  	   fi
- 	   fi
- 	 fi
- 	 if [ $update == 0 ] 
- 	 then
- 	   info=
- 	 else
-	echo -e "\033[34m==InfoBox===================================================\033[0m"
-	echo -e "\033[34m|\033[32mNew Update online (V.$last_vers). Option (u) = Direct UPDATE\033[0m"
-	 fi
-	echo -e "\033[34m============================================================\033[0m"
-	echo "          TNT V.$version - by NeoCooler aka krisjanne"
-	echo -e "\033[34m============================================================\033[0m"
-	echo "-> MAIN MENU"
-	echo
-	echo "     1 - Update Menu"
-	echo "     2 - Applications Menu"
-	echo "     3 - "
-	echo
-	echo "     b - Android build AOSP"
-	echo
-	echo "     k - Run Dsixda's Android Kitchen"
-	echo
-	echo "     x - Exit"
-	echo
-	echo
-	echo -e -n "\033[32m Choose option: \033[0m"
-	read tntopt
-	echo
-	echo
-
-    if [ "$?" != "1" ]
-      then
+if [ "$?" != "1" ]
+then
 	case "$tntopt" in
-	    1 ) clear; script/update $version; continue;;
-	    2 ) clear; script/app $version; continue;;
-	    b ) clear; script/build_aosp $version; continue;;
-	    u ) clear; script/updater $version; continue;;
-	    k ) clear; cd ~/kitchen; ./menu; clear; continue;;
-	    x ) clear; echo -e "\033[31mGoodbey !\033[0m"; echo; exit 1;;
-	    * ) echo -e "\033[31m Invalid option\033[0m";;
+		1 ) clear; tnt_store/tnt_store $version; continue;;
+		2 ) clear; android_tools/app_android_app $version; continue;;
+		u ) clear; update/update $version; continue;;
+		n ) clear; update/updater $version; continue;;
+		x ) clear; echo -e "$Blue_B" "Goodbey !" "$NORMAL"; echo; exit 1;;
+		* ) echo -e "$Red_B" " Invalid option" "$NORMAL";;
 	esac
-    fi
-  
-    script/press_enter
-
+fi
+script/press_enter
 done
-
-exit 0;
