Fix updater with new conf

diff --git a/update/update b/update/update
--- a/update/update
+++ b/update/update
@@ -11,43 +11,42 @@
 
 vers=$1
 
+source script/colors
+echo -e "$NORMALE"
+
 while : 
 do
-	clear
+clear
+echo -e "$Cyan" "============================================================" "$NORMAL"
+echo -e "     $Green_BU"" ToolsNeoTeam V.$vers - by NeoCooler aka krisjanne" "$NORMAL"
+echo -e "$Cyan" "============================================================" "$NORMAL"
+echo -e "$Cyan" "->$NORMAL$White UPDATE MENU$NORMAL"
+echo -e "$Magenta"
+echo -e "     1 -$White_K Update All Packages.$Magenta"
+echo -e "     2 -$White_K Upgrade Systeme Packages.$Magenta"
+echo -e "     3 -$White_K Upgrade & install new Systeme Packages.$Magenta"
+echo
+echo -e "     4 -$White_K Check update for TNT.$Magenta"
+echo
+echo -e "     x -$White_K Return MAIN MENU.$Magenta"
+echo -e "$NORMAL"
+echo -e -n "$Yellow" " Choose option:" "$White_B"
+read tntopt
+echo
+echo -e "$NORMAL"
 
-	echo -e "\033[34m============================================================\033[0m"
-	echo "          TNT V.$vers - by NeoCooler aka krisjanne"
-	echo -e "\033[34m============================================================\033[0m"
-	echo "-> UPDATE MENU"
-	echo
-	echo "     1 - Update All Packages"
-	echo "     2 - Upgrade Systeme Packages"
-	echo "     3 - Upgrade & install new Systeme Packages"
-	echo
-	echo "Info System Actuelle:"
-	cat /etc/issue | sed -e 's/n//'\ | sed -e 's/l//'\ | sed -e 's/n//'\;
-	echo
-	echo "     4 - Sync TNT with github Package"
-	echo
-	echo "     x - Return MAIN MENU"
-	echo
-	echo
-	echo -e -n "\033[32m Choose option:\033[0m"
-	read tntoption
-	echo
-	echo
-	echo
-	 
-	case "$tntoption" in
-	    1 ) clear; sudo apt-get update; clear;;
-	    2 ) clear; sudo apt-get upgrade; clear;;
-	    3 ) clear; sudo apt-get dist-upgrade; clear;;
-	    4 ) clear; script/updater $vers; continue;;
-	    x ) clear; exit 0;;
-	    * ) echo -e "\033[31m Invalid option\033[0m";;
-	esac
-
-    script/press_enter
+if [ "$?" != "1" ]
+then
+case "$tntopt" in
+	1 ) clear; sudo apt-get update; clear;;
+	2 ) clear; sudo apt-get upgrade; clear;;
+	3 ) clear; sudo apt-get dist-upgrade; clear;;
+	4 ) clear; update/updater $vers; continue;;
+	x ) clear; exit 0;;
+	* ) echo -e "\033[31m Invalid option\033[0m";;
+esac
+fi
+script/press_enter
 
 done
 exit 0;
